application: light-programming-interface
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: LPI.application